# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDOsYlcVmrmwnx48kSyip4SBiz9EKHGs
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset, Subset
import random
import numpy as np
import re
import os
from collections import Counter

# Control randomness (roughly)
seed = 123
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)

# Device configuration (GPU if available, otherwise CPU)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# Hyperparameters
learning_rate = 0.001
batch_size = 64
num_epochs = 30
embedding_dim = 128
hidden_dim = 256         # Increased for higher accuracy
max_length = 200
vocab_size = 10000

# ==================== Download IMDB Dataset ====================

print("Downloading IMDB dataset...")
!wget -q http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
!tar -xzf aclImdb_v1.tar.gz

# ==================== Tokenizer ====================

def simple_tokenizer(text):
    text = text.lower()
    tokens = re.findall(r'\b\w+\b', text)
    return tokens

# ==================== Load Data ====================

def load_imdb_data(data_dir, split='train'):
    texts = []
    labels = []

    pos_dir = os.path.join(data_dir, split, 'pos')
    for filename in os.listdir(pos_dir):
        if filename.endswith('.txt'):
            with open(os.path.join(pos_dir, filename), 'r', encoding='utf-8') as f:
                texts.append(f.read())
                labels.append(1)

    neg_dir = os.path.join(data_dir, split, 'neg')
    for filename in os.listdir(neg_dir):
        if filename.endswith('.txt'):
            with open(os.path.join(neg_dir, filename), 'r', encoding='utf-8') as f:
                texts.append(f.read())
                labels.append(0)

    return texts, labels

train_texts, train_labels = load_imdb_data('aclImdb', 'train')
test_texts, test_labels = load_imdb_data('aclImdb', 'test')

# ==================== Build Vocabulary ====================

word_counts = Counter()
for text in train_texts:
    tokens = simple_tokenizer(text)
    word_counts.update(tokens)

most_common = word_counts.most_common(vocab_size - 2)

vocab = {'<pad>': 0, '<unk>': 1}
for idx, (word, _) in enumerate(most_common, start=2):
    vocab[word] = idx

# ==================== Text to Indices ====================

def text_to_indices(text, vocab, max_length):
    tokens = simple_tokenizer(text)
    indices = [vocab.get(token, vocab['<unk>']) for token in tokens]

    if len(indices) < max_length:
        indices += [vocab['<pad>']] * (max_length - len(indices))
    else:
        indices = indices[:max_length]

    return torch.tensor(indices, dtype=torch.long)

# ==================== Custom Dataset ====================

class IMDBDataset(Dataset):
    def __init__(self, texts, labels, vocab, max_length):
        self.data = []
        self.labels = []

        for text, label in zip(texts, labels):
            self.data.append(text_to_indices(text, vocab, max_length))
            self.labels.append(label)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]

train_dataset_full = IMDBDataset(train_texts, train_labels, vocab, max_length)
test_dataset_full = IMDBDataset(test_texts, test_labels, vocab, max_length)

# Subset to match assignment requirement
g = torch.Generator()
g.manual_seed(seed)
train_idx = torch.randperm(len(train_dataset_full), generator=g)[:10000]
test_idx = torch.randperm(len(test_dataset_full), generator=g)[:2000]

train_dataset = Subset(train_dataset_full, train_idx)
test_dataset = Subset(test_dataset_full, test_idx)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

# ==================== Improved RNN Model ====================

class RNN(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, num_classes=2):
        super(RNN, self).__init__()

        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)

        self.lstm = nn.LSTM(
            embedding_dim,
            hidden_dim,
            num_layers=2,
            dropout=0.4,
            bidirectional=True,
            batch_first=True
        )

        self.dropout = nn.Dropout(0.5)
        self.fc = nn.Linear(hidden_dim * 2, num_classes)

    def forward(self, x):
        x = self.embedding(x)                      # (batch, seq, embed)
        out, (h, c) = self.lstm(x)                 # h has shape (4, batch, hidden)
        last_forward = h[-2]                       # last layer forward
        last_backward = h[-1]                      # last layer backward
        final = torch.cat((last_forward, last_backward), dim=1)

        final = self.dropout(final)
        return self.fc(final)

model = RNN(len(vocab), embedding_dim, hidden_dim).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

print(model)

# ==================== Training ====================

model.train()
for epoch in range(num_epochs):
    total_loss = 0

    for texts, labels in train_loader:
        texts = texts.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()
        outputs = model(texts)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {total_loss / len(train_loader):.4f}")

# ==================== Testing ====================

model.eval()
correct = 0
total = 0

with torch.no_grad():
    for texts, labels in test_loader:
        texts = texts.to(device)
        labels = labels.to(device)

        outputs = model(texts)
        predicted = outputs.argmax(1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

accuracy = 100 * correct / total
print(f"\nFinal Accuracy: {accuracy:.2f}%")