# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Eo8-YSzGlpW9HP4WqJT7NCH7D4K8NLS

#Problem 1
"""

a = input()
b = input()
a = int(a)
b = int(b)

day = 0

while (True):
  day = day + 1
  if (day % 2) == 1:
    a = a + 10000
    b = b * 1.02
  else :
    a = a * 1.07
    b = b * 1.02
  if (a > b) :
    print(day)
    break