# -*- coding: utf-8 -*-
"""Untitled150.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Eo8-YSzGlpW9HP4WqJT7NCH7D4K8NLS

#Problem 1 Kitsch
"""

def is_kitsch(a, b):
    a_str = str(a)
    b_str = str(b)
    i = j = 0
    while i < len(a_str) and j < len(b_str):
        if a_str[i] == b_str[j]:
            i += 1
            j += 1
        else:
            i += 1
    return j == len(b_str)

# Example usage:
a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))

if is_kitsch(a, b):
    print("YES")
else:
    print("NO")